services:
  db:
    image: postgres:13-alpine
    container_name: user_points_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123}
      POSTGRES_DB: ${POSTGRES_DB:-user_points}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user_points_app

    environment:
      CONFIG_PATH: ./config/config.yaml
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    restart: unless-stopped

volumes:
  postgres_data: