storage:
  user: "postgres"
  password: "123"
  host: "localhost"
  port: "5432"
  dbname: "user_points"
  sslmode: "disable"

rest:
  host: "localhost"
  port: "8080"

jwt:
  secretkey: "secret"
  tokenduration: "1h"